sayings = (
    "Don't be afraid of things because they're easy to do\n",
    "You don't have to be ashamed of using your own ideas\n",
    "Once the search is in progress, something will be found\n",
    "Remember those quiet evenings\n",
    "Be less critical more often\n",
    "Use fewer notes\n",
    "You can only make one dot at a time\n",
    "What is the reality of the situation?\n",
    "Emphasize repititions\n",
    "Do the washing up\n",
    "How would you have done it?\n",
    "Don't be frightened of cliches\n",
    "Lost in useless territory\n",
    "Cut a vital connection\n",
    "State the problem in words as clearly as possible\n",
    "Simple Subtraction\n",
    "Do we need holes?\n",
    "Ask your body\n",
    "Faced with a choice, do both\n",
    "Retrace your steps\n",
    "Emphasize the flaws\n",
    "Towards the insignificant\n",
    "Balance the consistency principle with the inconsistency principle\n",
    "Question the heroic approach\n",
    "Change nothing and continue with immaculate consistency\n",
    "Don't stress one thing more than another\n",
    "Is there something missing?\n"
)
